name: Keep Streamlit Alive

on:
  schedule:
    # 每小時執行一次
    - cron: "0 * * * *"

  # 可手動觸發工作流程（非必須）
  workflow_dispatch:

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Selenium Script
        run: python keep_alive.py
